### ISSUE TITLE
Please support MIT and other licenses without a copyright line

### ISSUE THREAD

**Issue by joshtriplett** [raftario/licensor#1]
Many projects (including Rust itself) use the MIT license *without* the line containing the year and copyright holder. (The Berne convention makes an actual copyright notice optional.) Please allow specifying a name like "MIT" to get just the license, without the un-substituted placeholders. (For instance, the license schema could have an option to delete the line containing the placeholders, and associated extra blank lines.)

**Comment by raftario** [comment]
`--no-copyright` flag will be available in v2 release

**Comment by joshtriplett** [comment]
Thank you. Would it be possible, for licenses that include the placeholder, to either automatically use `--no-copyright` if you don't supply a copyright holder, or error with a message saying you either need to pass `--no-copyright` or a copyright holder?

**Comment by raftario** [comment]
Would replacing the flag with a `--placeholder` flag make more sense ? That would allow people who still want the placeholders to keep them.

**Comment by joshtriplett** [comment]
@raftario Yes, that's even better! That sounds like the ideal interface:

- License name alone gets you the bare license.
- License name plus copyright holder fills in the placeholders.
- License name plus `--placeholder` leaves the placeholders for you to fill in.

**Comment by raftario** [comment]
All good!

**Comment by raftario** [comment]
@joshriplett On a similar note, the SPDX spec states that some parts of a license can be marked as optionnal. Do you think it would be a better default to include or exclude those ?

**Comment by raftario** [comment]
Closed by da7d1bf33f8f505f995966ab34c39dcf38c1b6ce

See #7 for further discussion on the optional parts.
