### ISSUE TITLE
Panics if writing to stdout fails

### ISSUE THREAD

**Issue by raftario** [raftario/licensor#3]
This is due to the [way the print macro works](https://doc.rust-lang.org/std/macro.print.html#panics).

Pointed out [on Reddit](https://www.reddit.com/r/rust/comments/d6od3i/licensor_write_licenses_to_stdout/f0vgwq8).

**Comment by Havvy** [comment]
https://crates.io/crates/calm_io may be a good solution to this.

**Comment by raftario** [comment]
Yeah I plan to use it, I'm currently rewriting most stuff to switch from a relatively low effort project to something decent. If you wanna include it in the current codebase feel free to do so, but I'd probably just wait a day or two for the new one.
