### ISSUE TITLE
Support skipping optional text as defined by the SPDX spec

### ISSUE THREAD

**Issue by raftario** [raftario/licensor#7]
The SPDX specs permit some parts of a license to be omitted while staying valid.

Should these fields be skipped or included by default ?

**Comment by raftario** [comment]
After looking at a couple licenses keeping them by default looks like a better idea.

**Comment by raftario** [comment]
Closed by 7f75a5e74045501afe1eb10ba3dbcc417e7602a5

**Comment by YodaEmbedding** [comment]
Github's license detection doesn't support optional text. See https://github.com/github/choosealicense.com/issues/634

Perhaps for MIT, the optional text should not be included by default?

**Comment by raftario** [comment]
Weird, it seems to work for me, but that might be due to skipping the copyright field. Is that an issue for the majority of licenses ? I'd much rather avoid change the behaviour of command line args depending on the license so if the default behaviour changes it'll be for all licenses.
